# coding: utf-8

"""
    QuestionsAPI

     QuestionsAPI helps you do operations with the scraped data. 🚀  ## Questions  You will be able to:  * **Put questions** (Create & Update & batch). * **Read questions**. * **Search questions**.   # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.question_query_model import QuestionQueryModel  # noqa: E501
from swagger_client.rest import ApiException


class TestQuestionQueryModel(unittest.TestCase):
    """QuestionQueryModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuestionQueryModel(self):
        """Test QuestionQueryModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.question_query_model.QuestionQueryModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
